import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { describe, expect, it } from "vitest";
import { repositoryRoot } from "../support/observer-fixtures.js";
import { withTemporaryDirectory } from "../support/temporary-directory.js";

type EnforceValidationTarget = "runtime" | "workbench" | "both";

interface EnforceValidationResult {
  readonly descriptorFailures: readonly string[];
  readonly consumerFailures: readonly string[];
}

interface EnforceContractValidatorModule {
  validateObserverEnforceContract(options?: {
    readonly root?: string;
    readonly target?: EnforceValidationTarget;
  }): EnforceValidationResult;
}

const validator = await import(
  new URL("../../scripts/validate-observer-enforce-contract.mjs", import.meta.url).href
) as EnforceContractValidatorModule;

const descriptorPath = "observer/protocol/generated/enforce-contract.json";
const runtimeProtocolPath = "observer/addon/Scripts/Game/ReforgerForgeObserver/RFO_ObserverProtocol.c";
const workbenchProtocolPath = "observer/workbench-addon/Scripts/WorkbenchGame/EnfusionMCP/EMCP_WB_ObserverProtocol.c";
const runtimeServicePath = "observer/addon/Scripts/Game/ReforgerForgeObserver/RFO_ObserverService.c";

const requiredFixtureFiles = [
  descriptorPath,
  runtimeProtocolPath,
  workbenchProtocolPath,
  "observer/addon/Scripts/Game/ReforgerForgeObserver/RFO_ObserverJob.c",
  "observer/addon/Scripts/Game/ReforgerForgeObserver/RFO_ObserverSession.c",
  runtimeServicePath,
  "observer/addon/Scripts/Game/ReforgerForgeObserver/RFO_ObserverCapabilities.c",
  "observer/addon/Scripts/Game/ReforgerForgeObserver/RFO_ObserverMailboxTransport.c",
  "observer/addon/Scripts/Game/ReforgerForgeObserver/RFO_ObserverCapture.c",
  "observer/workbench-addon/Scripts/WorkbenchGame/EnfusionMCP/EMCP_WB_ObserverCommon.c",
  "src/workbench/observer-adapter.ts",
  "scripts/run-workbench-observer-acceptance.ts",
  "scripts/run-runtime-observer-acceptance.ts",
] as const;

function fixturePath(root: string, relativePath: string): string {
  return join(root, ...relativePath.split("/"));
}

function createFixture(root: string): string {
  for (const relativePath of requiredFixtureFiles) {
    const destination = fixturePath(root, relativePath);
    mkdirSync(dirname(destination), { recursive: true });
    copyFileSync(fixturePath(repositoryRoot, relativePath), destination);
  }
  return root;
}

function readFixture(root: string, relativePath: string): string {
  return readFileSync(fixturePath(root, relativePath), "utf8");
}

function writeFixture(root: string, relativePath: string, contents: string): void {
  writeFileSync(fixturePath(root, relativePath), contents, "utf8");
}

function replaceOnce(source: string, expected: string, replacement: string): string {
  expect(source).toContain(expected);
  return source.replace(expected, replacement);
}

function validate(root: string, target: EnforceValidationTarget = "both"): EnforceValidationResult {
  return validator.validateObserverEnforceContract({ root, target });
}

function scopedIt(
  name: string,
  run: (root: string) => Promise<void> | void,
): void {
  it(name, () => withTemporaryDirectory((root) => run(createFixture(root)), { prefix: "rfo-enforce-validator-" }));
}

describe("observer Enforce contract static validator", () => {
  scopedIt("accepts the current generated descriptor, C classes, and named consumers", (root) => {
    const result = validate(root);

    expect(result.descriptorFailures).toEqual([]);
    expect(result.consumerFailures).toEqual([]);
  });

  scopedIt("categorizes descriptor JSON-to-C drift before inspecting consumers", (root) => {
    const descriptor = JSON.parse(readFixture(root, descriptorPath)) as {
      targets: { game: { strings: Array<{ field: string; value: string }> } };
    };
    const capability = descriptor.targets.game.strings.find(({ field }) => field === "CAP_RENDER_CAPTURE");
    expect(capability).toBeDefined();
    capability!.value = "render.capture.fixture-drift";
    writeFixture(root, descriptorPath, `${JSON.stringify(descriptor, null, 2)}\n`);

    const result = validate(root, "runtime");

    expect(result.descriptorFailures).toContain(
      `runtime descriptor and generated C disagree (${runtimeProtocolPath})`
    );
    expect(result.consumerFailures).toEqual([]);
  });

  it.each([
    ["header", (source: string) => replaceOnce(
      source,
      "// Generated by npm run protocol:generate from observer/protocol/enforce-contract.ts. Do not edit.",
      "// stale generated header"
    )],
    ["member", (source: string) => replaceOnce(
      source,
      'static const string CAP_RENDER_CAPTURE = "render.capture";',
      'static const string CAP_RENDER_CAPTURE = "render.capture.stale";'
    )],
    ["class", (source: string) => replaceOnce(
      source,
      "class RFO_ObserverProtocol",
      "class RFO_ObserverProtocolStale"
    )],
  ] as const)("categorizes generated C %s drift as descriptor drift", (_kind, mutate) => withTemporaryDirectory((temporaryRoot) => {
    const root = createFixture(temporaryRoot);
    writeFixture(root, runtimeProtocolPath, mutate(readFixture(root, runtimeProtocolPath)));

    const result = validate(root, "runtime");

    expect(result.descriptorFailures).toContain(
      `runtime descriptor and generated C disagree (${runtimeProtocolPath})`
    );
    expect(result.consumerFailures).toEqual([]);
  }, { prefix: "rfo-enforce-validator-" }));

  scopedIt("categorizes a named consumer's raw protocol bypass separately from descriptor drift", (root) => {
    writeFixture(
      root,
      runtimeServicePath,
      `${readFixture(root, runtimeServicePath)}\n\tstring fixtureRawProtocolBypass = "CAPTURE_TIMEOUT";\n`
    );

    const result = validate(root, "runtime");

    expect(result.descriptorFailures).toEqual([]);
    expect(result.consumerFailures).toContain(
      'Game service still spells raw protocol literal "CAPTURE_TIMEOUT"'
    );
  });

  scopedIt("permits comments, JSON keys, and reviewed tuning literals in named consumers", (root) => {
    const service = readFixture(root, runtimeServicePath);
    const fixtureComment = "\t// Documentation can quote \"CAPTURE_TIMEOUT\" and \"1.0\" without bypassing the protocol.\n";
    const fixtureLiterals = [
      "\t\tstring fixtureJsonKey = \"protocolVersion\";",
      "\t\tfloat fixtureReviewedTuning = 0.001;",
    ].join("\n");
    writeFixture(
      root,
      runtimeServicePath,
      replaceOnce(
        service,
        "\t\tstring result = \"[\";",
        `${fixtureLiterals}\n\t\tstring result = \"[\";`
      ).replace("\tprotected string BuildStringArray", `${fixtureComment}\tprotected string BuildStringArray`)
    );

    const result = validate(root, "runtime");

    expect(result.descriptorFailures).toEqual([]);
    expect(result.consumerFailures).toEqual([]);
  });
});
