import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  CAPABILITY_REGISTRY,
  ERROR_REGISTRY,
  type ObserverCapabilityDefinition,
  type ObserverErrorDefinition,
} from "../observer/protocol/registry.js";
import {
  GAME_ENFORCE_PROTOCOL_OUTPUT,
  OBSERVER_ENFORCE_CONTRACT,
  WORKBENCH_ENFORCE_PROTOCOL_OUTPUT,
  createObserverEnforceContract,
  validateObserverEnforceContract,
  type EnforceContractSource,
  type EnforceTargetContract,
  type ObserverEnforceContract,
} from "../observer/protocol/enforce-contract.js";

export interface ProtocolRegistrySource {
  errorRegistry: Readonly<Record<string, ObserverErrorDefinition>>;
  capabilityRegistry: Readonly<Record<string, ObserverCapabilityDefinition>>;
  /** Optional fixture seam; production derives this from the same registries. */
  enforceContract?: ObserverEnforceContract;
  /** Optional scalar fixture overrides used only when no complete contract is supplied. */
  enforceContractSource?: Omit<EnforceContractSource, "errorRegistry" | "capabilityRegistry">;
}

export const CANONICAL_PROTOCOL_REGISTRIES: ProtocolRegistrySource = {
  errorRegistry: ERROR_REGISTRY,
  capabilityRegistry: CAPABILITY_REGISTRY,
  enforceContract: OBSERVER_ENFORCE_CONTRACT,
};

export const PROTOCOL_ARTIFACT_PATHS = [
  "observer/protocol/generated/error-codes.json",
  "observer/protocol/generated/runtime-error-codes.json",
  "observer/protocol/generated/capabilities.json",
  "observer/protocol/generated/fixed-error-messages.json",
  "observer/protocol/generated/enforce-contract.json",
  "observer/addon/Scripts/Game/ReforgerForgeObserver/RFO_ObserverProtocol.c",
  "observer/workbench-addon/Scripts/WorkbenchGame/EnfusionMCP/EMCP_WB_ObserverProtocol.c",
  "observer/protocol/schemas/artifact-manifest.schema.json",
  "observer/protocol/schemas/capture-request.schema.json",
  "observer/protocol/schemas/error.schema.json",
  "observer/protocol/schemas/heartbeat.schema.json",
  "observer/protocol/schemas/instance-registration.schema.json",
  "observer/protocol/schemas/job-status.schema.json",
  "observer/protocol/schemas/session-contract.schema.json",
  "observer/protocol/schemas/vocabulary.schema.json",
  "observer/protocol/errors.md",
  "observer/protocol/capabilities.md",
] as const;

export type ProtocolArtifactPath = (typeof PROTOCOL_ARTIFACT_PATHS)[number];
export type ProtocolArtifacts = ReadonlyMap<ProtocolArtifactPath, string>;

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
export const repositoryRoot = resolve(scriptDirectory, "..");

function json(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

export const ENFORCE_PROTOCOL_HEADER =
  "// Generated by npm run protocol:generate from observer/protocol/enforce-contract.ts. Do not edit.";

/** Escape the subset of Enforce string syntax used by literal-only protocol classes. */
export function escapeEnforceStringLiteral(value: string): string {
  if (value.includes("\0")) throw new Error("Enforce string literals must not contain NUL");
  let rendered = "";
  for (const character of value) {
    const code = character.codePointAt(0);
    if (code === undefined) throw new Error("Could not read Enforce string character");
    if (character === "\\") rendered += "\\\\";
    else if (character === "\"") rendered += "\\\"";
    else if (character === "\r") rendered += "\\r";
    else if (character === "\n") rendered += "\\n";
    else if (character === "\t") rendered += "\\t";
    else if (code < 0x20 || code === 0x7f) rendered += `\\x${code.toString(16).padStart(2, "0")}`;
    else rendered += character;
  }
  return rendered;
}

function expandScientificNotation(value: string): string {
  if (!/[eE]/.test(value)) return value;
  const match = /^(-?)(\d+)(?:\.(\d*))?[eE]([+-]?\d+)$/.exec(value);
  if (!match) throw new Error(`Could not render Enforce float ${value}`);
  const [, sign, whole, fraction = "", exponentText] = match;
  const digits = `${whole}${fraction}`;
  const decimalIndex = whole.length + Number(exponentText);
  if (decimalIndex <= 0) return `${sign}0.${"0".repeat(-decimalIndex)}${digits}`;
  if (decimalIndex >= digits.length) return `${sign}${digits}${"0".repeat(decimalIndex - digits.length)}`;
  return `${sign}${digits.slice(0, decimalIndex)}.${digits.slice(decimalIndex)}`;
}

/** Render only finite, Enforce-safe scalar numbers with a stable decimal form. */
export function renderEnforceNumberLiteral(value: number, kind: "int" | "float"): string {
  if (!Number.isFinite(value)) throw new Error("Enforce numeric literals must be finite");
  if (kind === "int") {
    if (!Number.isSafeInteger(value)) throw new Error("Enforce integer literals must be safe integers");
    return String(value);
  }
  if (kind !== "float") {
    throw new Error(`Unsupported Enforce numeric kind ${JSON.stringify(kind)}`);
  }
  if (Math.abs(value) > 3.402823466e38) {
    throw new Error("Enforce float literals must fit a 32-bit finite float");
  }
  const decimal = expandScientificNotation(String(Object.is(value, -0) ? 0 : value));
  return decimal.includes(".") ? decimal : `${decimal}.0`;
}

function assertLiteralOnlyTarget(target: EnforceTargetContract): void {
  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(target.className)) {
    throw new Error(`Unsupported Enforce class name ${JSON.stringify(target.className)}`);
  }
  const fields = new Set<string>();
  for (const entry of [...target.strings, ...target.numbers]) {
    if (!/^[A-Z][A-Z0-9_]*$/.test(entry.field)) {
      throw new Error(`Invalid Enforce field name ${JSON.stringify(entry.field)}`);
    }
    if (fields.has(entry.field)) throw new Error(`Duplicate Enforce field ${entry.field}`);
    fields.add(entry.field);
  }
  if (fields.size === 0) throw new Error(`Enforce target ${target.className} has no literal vocabulary`);
}

/** Render a standalone, literal-only Enforce declaration with deterministic LF endings. */
export function renderEnforceProtocolClass(target: EnforceTargetContract): string {
  assertLiteralOnlyTarget(target);
  return [
    ENFORCE_PROTOCOL_HEADER,
    `class ${target.className}`,
    "{",
    ...target.strings.map((entry) =>
      `\tstatic const string ${entry.field} = "${escapeEnforceStringLiteral(entry.value)}";`
    ),
    ...target.numbers.map((entry) =>
      `\tstatic const ${entry.kind} ${entry.field} = ${renderEnforceNumberLiteral(entry.value, entry.kind)};`
    ),
    "}",
    "",
  ].join("\n");
}

export function enforceContractDescriptor(contract: ObserverEnforceContract): Readonly<Record<string, unknown>> {
  validateObserverEnforceContract(contract);
  return {
    descriptorVersion: contract.descriptorVersion,
    identities: contract.identities,
    terminalStates: contract.terminalStates,
    targets: {
      game: contract.targets.game,
      workbench: contract.targets.workbench,
    },
    backendTuning: contract.backendTuning,
  };
}

function enforceContractFor(source: ProtocolRegistrySource): ObserverEnforceContract {
  const contract = source.enforceContract ?? createObserverEnforceContract({
    errorRegistry: source.errorRegistry,
    capabilityRegistry: source.capabilityRegistry,
    ...source.enforceContractSource,
  });
  validateObserverEnforceContract(contract);
  if (contract.targets.game.outputPath !== GAME_ENFORCE_PROTOCOL_OUTPUT) {
    throw new Error(`Game Enforce target must output ${GAME_ENFORCE_PROTOCOL_OUTPUT}`);
  }
  if (contract.targets.workbench.outputPath !== WORKBENCH_ENFORCE_PROTOCOL_OUTPUT) {
    throw new Error(`Workbench Enforce target must output ${WORKBENCH_ENFORCE_PROTOCOL_OUTPUT}`);
  }
  return contract;
}

function markdownCell(value: string): string {
  return value
    .replaceAll("\\", "\\\\")
    .replaceAll("|", "\\|")
    .replaceAll("\r\n", "<br>")
    .replaceAll("\n", "<br>")
    .replaceAll("\r", "<br>");
}

function stringEnum(values: readonly string[]): { type: "string"; enum: string[] } {
  if (values.length === 0) {
    throw new Error("Generated protocol vocabulary enums must not be empty");
  }
  return { type: "string", enum: [...values] };
}

function contractString(target: EnforceTargetContract, field: string): string {
  const value = target.strings.find((entry) => entry.field === field)?.value;
  if (value === undefined) throw new Error(`Enforce contract target ${target.className} is missing ${field}`);
  return value;
}

function compatibleProtocolPattern(version: string): string {
  const match = /^(\d+)\.\d+$/.exec(version);
  if (!match) throw new Error(`Runtime protocol ${JSON.stringify(version)} does not have a numeric major/minor identity`);
  return `^${match[1]}\\.[0-9]+$`;
}

const ARTIFACT_MANIFEST_SCHEMA_TEMPLATE = String.raw`{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://reforger-forge.dev/observer/v1/artifact-manifest.schema.json",
  "$comment": "Generated by npm run protocol:generate. Do not edit.",
  "title": "Observer artifact completion manifest",
  "type": "object",
  "required": ["protocolVersion", "sessionId", "instanceId", "instanceNonce", "jobId", "artifactId", "relativeScreenshotFilename", "screenshotIssuedAt", "completedAt", "worldId", "worldEpoch", "actualCamera", "requestedSettleFrames", "actualSettleFrames", "contaminated", "warnings"],
  "properties": {
    "protocolVersion": { "type": "string", "pattern": "__RUNTIME_PROTOCOL_PATTERN__" },
    "sessionId": { "$ref": "#/$defs/id" },
    "instanceId": { "$ref": "#/$defs/id" },
    "instanceNonce": { "type": "string", "minLength": 32, "maxLength": 256 },
    "jobId": { "$ref": "#/$defs/id" },
    "artifactId": { "$ref": "#/$defs/id" },
    "relativeScreenshotFilename": { "type": "string", "pattern": "^[A-Za-z0-9_-]{1,96}\\.(bmp|png)$" },
    "screenshotIssuedAt": { "type": "string", "format": "date-time" },
    "completedAt": { "type": "string", "format": "date-time" },
    "expectedByteCount": { "type": "integer", "minimum": 1, "maximum": 67108864 },
    "worldId": { "oneOf": [{ "type": "string", "minLength": 1, "maxLength": 512 }, { "type": "null" }] },
    "worldEpoch": { "type": "integer", "minimum": 0 },
    "actualCamera": { "type": "object" },
    "actualFov": { "type": "number", "minimum": 1, "maximum": 179 },
    "requestedSettleFrames": { "type": "integer", "minimum": 0, "maximum": 30 },
    "actualSettleFrames": { "type": "integer", "minimum": 0, "maximum": 30 },
    "contaminated": { "type": "boolean" },
    "warnings": { "type": "array", "maxItems": 16, "items": { "type": "string", "maxLength": 256 } }
  },
  "$defs": { "id": { "type": "string", "pattern": "^[A-Za-z0-9_-]{1,96}$" } }
}`;

const CAPTURE_REQUEST_SCHEMA_TEMPLATE = String.raw`{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://reforger-forge.dev/observer/v1/capture-request.schema.json",
  "$comment": "Generated by npm run protocol:generate. Do not edit.",
  "title": "Observer capture request",
  "type": "object",
  "required": ["protocolVersion", "jobId", "idempotencyKey", "deadlineAt", "view", "settleFrames", "performancePolicy"],
  "properties": {
    "protocolVersion": { "type": "string", "pattern": "__RUNTIME_PROTOCOL_PATTERN__" },
    "jobId": { "$ref": "#/$defs/id" },
    "idempotencyKey": { "type": "string", "minLength": 1, "maxLength": 128 },
    "instanceId": { "$ref": "#/$defs/id" },
    "worldEpoch": { "type": "integer", "minimum": 0 },
    "deadlineAt": { "type": "string", "format": "date-time" },
    "view": {
      "oneOf": [
        { "type": "object", "required": ["kind"], "properties": { "kind": { "const": "current" } } },
        { "type": "object", "required": ["kind", "position", "orientation", "fov"], "properties": { "kind": { "const": "pose" }, "position": { "$ref": "#/$defs/vector3" }, "orientation": { "$ref": "#/$defs/quaternion" }, "fov": { "type": "number", "minimum": 1, "maximum": 179 } } },
        { "type": "object", "required": ["kind", "position", "target", "fov"], "properties": { "kind": { "const": "lookAt" }, "position": { "$ref": "#/$defs/vector3" }, "target": { "$ref": "#/$defs/vector3" }, "fov": { "type": "number", "minimum": 1, "maximum": 179 } } }
      ]
    },
    "settleFrames": { "type": "integer", "minimum": 0, "maximum": 30 },
    "performancePolicy": { "enum": ["evidence", "instrumented", "performance"] }
  },
  "$defs": {
    "id": { "type": "string", "pattern": "^[A-Za-z0-9_-]{1,96}$" },
    "vector3": { "type": "array", "minItems": 3, "maxItems": 3, "items": { "type": "number" } },
    "quaternion": { "type": "array", "minItems": 4, "maxItems": 4, "items": { "type": "number" } }
  }
}`;

const INSTANCE_REGISTRATION_SCHEMA_TEMPLATE = String.raw`{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://reforger-forge.dev/observer/v1/instance-registration.schema.json",
  "$comment": "Generated by npm run protocol:generate from observer/protocol/registry.ts. Do not edit.",
  "title": "Observer instance registration",
  "type": "object",
  "required": ["protocolVersion", "addonVersion", "bundleDigest", "buildIdentity", "agentInstanceId", "sessionId", "launchNonce", "instanceId", "instanceNonce", "runtimeKind", "capabilities", "selectedTransport", "headless", "worldId", "worldEpoch", "registeredAt"],
  "properties": {
    "protocolVersion": { "type": "string", "pattern": "__RUNTIME_PROTOCOL_PATTERN__" },
    "addonVersion": { "type": "string" },
    "bundleDigest": { "type": "string", "pattern": "^[a-f0-9]{64}$" },
    "buildIdentity": { "type": "string", "pattern": "^[a-f0-9]{64}$" },
    "agentInstanceId": { "$ref": "#/$defs/id" },
    "sessionId": { "$ref": "#/$defs/id" },
    "launchNonce": { "type": "string", "minLength": 32, "maxLength": 256 },
    "instanceId": { "$ref": "#/$defs/id" },
    "instanceNonce": { "type": "string", "minLength": 32, "maxLength": 256 },
    "processId": { "type": "integer", "minimum": 1 },
    "runtimeKind": { "enum": ["client", "listenServer", "dedicated", "workbench", "testRunner"] },
    "capabilities": { "type": "array", "maxItems": 64, "items": { "type": "string", "minLength": 1, "maxLength": 64 } },
    "selectedTransport": { "enum": ["rest", "mailbox"] },
    "headless": { "type": "boolean" },
    "worldId": { "oneOf": [{ "type": "string", "minLength": 1, "maxLength": 512 }, { "type": "null" }] },
    "worldEpoch": { "type": "integer", "minimum": 0 },
    "registeredAt": { "type": "string", "format": "date-time" }
  },
  "$defs": {
    "id": { "type": "string", "pattern": "^[A-Za-z0-9_-]{1,96}$" },
    "knownCapability": { "type": "string", "enum": "__CAPABILITIES__" }
  }
}`;

const SESSION_CONTRACT_SCHEMA_TEMPLATE = String.raw`{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://reforger-forge.dev/observer/v1/session-contract.schema.json",
  "$comment": "Generated by npm run protocol:generate. Do not edit.",
  "title": "Observer session contract",
  "type": "object",
  "required": ["protocolVersion", "addonVersion", "bundleDigest", "buildIdentity", "expectedRuntimeKind", "sessionId", "launchNonce", "sessionToken", "createdAt", "expiresAt", "agent", "transportPreference", "profileDirectoryName", "limits"],
  "properties": {
    "protocolVersion": { "type": "string", "pattern": "__RUNTIME_PROTOCOL_PATTERN__" },
    "addonVersion": { "type": "string", "maxLength": 32 },
    "bundleDigest": { "type": "string", "pattern": "^[a-f0-9]{64}$" },
    "buildIdentity": { "type": "string", "pattern": "^[a-f0-9]{64}$" },
    "expectedRuntimeKind": { "enum": ["client", "listenServer", "dedicated", "workbench", "testRunner"] },
    "sessionId": { "$ref": "#/$defs/id" },
    "launchNonce": { "$ref": "#/$defs/secret" },
    "sessionToken": { "$ref": "#/$defs/secret" },
    "createdAt": { "type": "string", "format": "date-time" },
    "expiresAt": { "type": "string", "format": "date-time" },
    "expiresAtUnix": { "type": "integer", "minimum": 1 },
    "agent": {
      "type": "object",
      "required": ["host", "port", "instanceId"],
      "properties": { "host": { "enum": ["127.0.0.1", "::1"] }, "port": { "type": "integer", "minimum": 1, "maximum": 65535 }, "instanceId": { "$ref": "#/$defs/id" } }
    },
    "transportPreference": { "type": "array", "minItems": 1, "maxItems": 2, "items": { "enum": ["rest", "mailbox"] } },
    "profileDirectoryName": { "const": "__SESSION_DIRECTORY_NAME__" },
    "limits": {
      "type": "object",
      "required": ["maxPendingJobs", "maxCaptureRatePerMinute", "maxArtifactBytes", "minFov", "maxFov", "maxSettleFrames", "maxCaptureDistance"],
      "properties": {
        "maxPendingJobs": { "type": "integer", "minimum": 1, "maximum": 64 },
        "maxCaptureRatePerMinute": { "type": "integer", "minimum": 1, "maximum": 600 },
        "maxArtifactBytes": { "type": "integer", "minimum": 1024, "maximum": 67108864 },
        "minFov": { "type": "integer", "minimum": 1, "maximum": 179 },
        "maxFov": { "type": "integer", "minimum": 1, "maximum": 179 },
        "maxSettleFrames": { "type": "integer", "minimum": 0, "maximum": 30 },
        "maxCaptureDistance": { "type": "integer", "minimum": 1, "maximum": 100000 }
      }
    }
  },
  "$defs": {
    "id": { "type": "string", "pattern": "^[A-Za-z0-9_-]{1,96}$" },
    "secret": { "type": "string", "pattern": "^[A-Za-z0-9_-]{32,256}$" }
  }
}`;

const ERROR_RESPONSE_SCHEMA_TEMPLATE = String.raw`{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://reforger-forge.dev/observer/v1/error.schema.json",
  "title": "Observer error response",
  "type": "object",
  "required": ["protocolVersion", "error"],
  "properties": {
    "protocolVersion": { "const": "__RUNTIME_PROTOCOL_VERSION__" },
    "error": { "type": "object", "required": ["code", "message"], "properties": { "code": { "type": "string", "enum": "__ERROR_CODES__" }, "message": { "type": "string", "maxLength": 512 } } }
  }
}`;

const HEARTBEAT_SCHEMA_TEMPLATE = String.raw`{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://reforger-forge.dev/observer/v1/heartbeat.schema.json",
  "title": "Observer heartbeat",
  "type": "object",
  "required": ["protocolVersion", "sessionId", "instanceId", "instanceNonce", "sequence", "sentAt", "worldId", "worldEpoch", "capabilities", "transportHealthy"],
  "properties": {
    "protocolVersion": { "type": "string", "pattern": "__RUNTIME_PROTOCOL_PATTERN__" },
    "sessionId": { "$ref": "#/$defs/id" },
    "instanceId": { "$ref": "#/$defs/id" },
    "instanceNonce": { "type": "string", "minLength": 32, "maxLength": 256 },
    "sequence": { "type": "integer", "minimum": 0 },
    "sentAt": { "type": "string", "format": "date-time" },
    "worldId": { "oneOf": [{ "type": "string", "minLength": 1, "maxLength": 512 }, { "type": "null" }] },
    "worldEpoch": { "type": "integer", "minimum": 0 },
    "capabilities": { "type": "array", "maxItems": 64, "items": { "type": "string", "maxLength": 64 } },
    "activeJobId": { "oneOf": [{ "$ref": "#/$defs/id" }, { "type": "null" }] },
    "cameraLeaseJobId": { "oneOf": [{ "$ref": "#/$defs/id" }, { "type": "null" }] },
    "transportHealthy": { "type": "boolean" },
    "lastErrorCode": {
      "oneOf": [
        { "type": "string", "enum": "__RUNTIME_ERROR_CODES__" },
        { "type": "null" }
      ]
    }
  },
  "$defs": { "id": { "type": "string", "pattern": "^[A-Za-z0-9_-]{1,96}$" } }
}`;

const JOB_STATUS_SCHEMA_TEMPLATE = String.raw`{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://reforger-forge.dev/observer/v1/job-status.schema.json",
  "title": "Observer job status",
  "type": "object",
  "required": ["protocolVersion", "sessionId", "instanceId", "instanceNonce", "jobId", "sequence", "state", "worldId", "worldEpoch", "timestamp"],
  "properties": {
    "protocolVersion": { "type": "string", "pattern": "__RUNTIME_PROTOCOL_PATTERN__" },
    "sessionId": { "$ref": "#/$defs/id" },
    "instanceId": { "$ref": "#/$defs/id" },
    "instanceNonce": { "type": "string", "minLength": 32, "maxLength": 256 },
    "jobId": { "$ref": "#/$defs/id" },
    "sequence": { "type": "integer", "minimum": 0 },
    "state": { "enum": "__JOB_STATES__" },
    "worldId": { "oneOf": [{ "type": "string", "minLength": 1, "maxLength": 512 }, { "type": "null" }] },
    "worldEpoch": { "type": "integer", "minimum": 0 },
    "timestamp": { "type": "string", "format": "date-time" },
    "deliveryToken": { "type": "string", "minLength": 16, "maxLength": 256, "pattern": "^[A-Za-z0-9_-]+$" },
    "cameraLease": {
      "oneOf": [
        {
          "type": "object",
          "required": ["held", "leaseId", "observerCameraId"],
          "properties": {
            "held": { "const": true },
            "leaseId": { "$ref": "#/$defs/id" },
            "observerCameraId": { "oneOf": [{ "$ref": "#/$defs/id" }, { "type": "integer", "minimum": 0 }] }
          }
        },
        {
          "type": "object",
          "required": ["held", "restorationConfirmed"],
          "properties": {
            "held": { "const": false },
            "restorationConfirmed": { "type": "boolean" }
          }
        }
      ]
    },
    "errorCode": { "type": "string", "enum": "__RUNTIME_ERROR_CODES__" },
    "message": { "type": "string", "maxLength": 512 }
  },
  "$defs": { "id": { "type": "string", "pattern": "^[A-Za-z0-9_-]{1,96}$" } }
}`;

function renderSchemaTemplate(
  template: string,
  replacements: Readonly<Record<string, unknown>>
): string {
  let rendered = template.trim().replaceAll("\r\n", "\n");
  for (const [name, values] of Object.entries(replacements)) {
    const marker = JSON.stringify(`__${name}__`);
    if (!rendered.includes(marker)) {
      throw new Error(`Protocol schema template is missing marker ${marker}`);
    }
    rendered = rendered.replaceAll(marker, JSON.stringify(values));
  }
  const unresolvedMarker = /__[A-Z][A-Z0-9_]*__/.exec(rendered)?.[0];
  if (unresolvedMarker) {
    throw new Error(`Protocol schema template has unresolved marker ${unresolvedMarker}`);
  }
  JSON.parse(rendered);
  return `${rendered}\n`;
}

function renderErrorsMarkdown(
  entries: ReadonlyArray<readonly [string, ObserverErrorDefinition]>
): string {
  const rows = entries.map(([code, definition]) => [
    code,
    definition.publicMessagePolicy,
    definition.retryable ? "yes" : "no",
    definition.backends.join(", "),
    markdownCell(definition.publicMessage),
  ].join(" | "));

  return [
    "# Observer protocol errors",
    "",
    "<!-- Generated by `npm run protocol:generate` from `observer/protocol/registry.ts`. Do not edit. -->",
    "",
    "Consumers branch on the stable code; diagnostic prose is bounded to 512 characters. A `fixed`",
    "message policy suppresses backend prose. Backend-private Workbench handler and lifecycle values",
    "are accepted only at the adapter boundary and mapped to their host equivalents before MCP",
    "publication.",
    "",
    "| Code | Message policy | Retryable | Applicable backends | Public/fallback message |",
    "|---|---|---:|---|---|",
    ...rows.map((row) => `| ${row} |`),
    "",
    "`RESTORATION_UNCONFIRMED` is a hard safety failure: the renderer remains unavailable until a",
    "later explicit state proves safe restoration.",
    "",
  ].join("\n");
}

function renderCapabilitiesMarkdown(
  entries: ReadonlyArray<readonly [string, ObserverCapabilityDefinition]>
): string {
  const rows = entries.map(([capability, definition]) => [
    `\`${markdownCell(capability)}\``,
    definition.backends.join(", "),
    markdownCell(definition.proof),
  ].join(" | "));

  return [
    "# Observer protocol capabilities",
    "",
    "<!-- Generated by `npm run protocol:generate` from `observer/protocol/registry.ts`. Do not edit. -->",
    "",
    "A capability is routable only on a backend listed below and only after that backend's producer",
    "proves initialization. Unknown claims remain diagnostic and are never used for routing.",
    "",
    "| Capability | Proving backend | Required proof |",
    "|---|---|---|",
    ...rows.map((row) => `| ${row} |`),
    "",
    "`entity.resolve` and `server.coordinate` are deliberately absent until an implementation and",
    "conformance test can prove them. Headless runtimes also strip render/camera claims; a runtime",
    "can never route `camera.editor` merely because that capability is globally known for Workbench.",
    "",
  ].join("\n");
}

/**
 * Render every registry-derived artifact in canonical registry insertion order.
 * The returned bytes are platform-independent (UTF-8 with LF line endings).
 */
export function renderProtocolArtifacts(
  source: ProtocolRegistrySource = CANONICAL_PROTOCOL_REGISTRIES
): ProtocolArtifacts {
  const enforceContract = enforceContractFor(source);
  const runtimeProtocolPattern = compatibleProtocolPattern(enforceContract.identities.runtimeObserver);
  const runtimeJobStates = enforceContract.targets.game.strings
    .filter((entry) => entry.field.startsWith("STATE_"))
    .map((entry) => entry.value);
  const sessionDirectoryName = contractString(enforceContract.targets.game, "DIRECTORY_SESSION_ROOT");
  const errorEntries = Object.entries(source.errorRegistry);
  const capabilityEntries = Object.entries(source.capabilityRegistry);
  const errorCodes = errorEntries.map(([code]) => code);
  const runtimeErrorCodes = errorEntries
    .filter(([, definition]) => definition.backends.includes("runtime"))
    .map(([code]) => code);
  const capabilities = capabilityEntries.map(([capability]) => capability);
  const runtimeCapabilities = capabilityEntries
    .filter(([, definition]) => definition.backends.includes("runtime"))
    .map(([capability]) => capability);
  const workbenchCapabilities = capabilityEntries
    .filter(([, definition]) => definition.backends.includes("workbench"))
    .map(([capability]) => capability);
  const fixedErrorMessages = Object.fromEntries(errorEntries
    .filter(([, definition]) => definition.publicMessagePolicy === "fixed")
    .map(([code, definition]) => [code, definition.publicMessage]));

  const vocabularySchema = {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $id: "https://reforger-forge.dev/observer/v1/vocabulary.schema.json",
    title: "Observer protocol registry vocabulary",
    $comment: "Generated by npm run protocol:generate from observer/protocol/registry.ts. Do not edit.",
    $defs: {
      errorCode: stringEnum(errorCodes),
      runtimeErrorCode: stringEnum(runtimeErrorCodes),
      capability: stringEnum(capabilities),
      runtimeCapability: stringEnum(runtimeCapabilities),
      workbenchCapability: stringEnum(workbenchCapabilities),
    },
  };

  return new Map<ProtocolArtifactPath, string>([
    ["observer/protocol/generated/error-codes.json", json(errorCodes)],
    ["observer/protocol/generated/runtime-error-codes.json", json(runtimeErrorCodes)],
    ["observer/protocol/generated/capabilities.json", json(capabilities)],
    ["observer/protocol/generated/fixed-error-messages.json", json(fixedErrorMessages)],
    ["observer/protocol/generated/enforce-contract.json", json(enforceContractDescriptor(enforceContract))],
    [
      "observer/addon/Scripts/Game/ReforgerForgeObserver/RFO_ObserverProtocol.c",
      renderEnforceProtocolClass(enforceContract.targets.game),
    ],
    [
      "observer/workbench-addon/Scripts/WorkbenchGame/EnfusionMCP/EMCP_WB_ObserverProtocol.c",
      renderEnforceProtocolClass(enforceContract.targets.workbench),
    ],
    ["observer/protocol/schemas/artifact-manifest.schema.json", renderSchemaTemplate(
      ARTIFACT_MANIFEST_SCHEMA_TEMPLATE,
      { RUNTIME_PROTOCOL_PATTERN: runtimeProtocolPattern }
    )],
    ["observer/protocol/schemas/capture-request.schema.json", renderSchemaTemplate(
      CAPTURE_REQUEST_SCHEMA_TEMPLATE,
      { RUNTIME_PROTOCOL_PATTERN: runtimeProtocolPattern }
    )],
    ["observer/protocol/schemas/error.schema.json", renderSchemaTemplate(
      ERROR_RESPONSE_SCHEMA_TEMPLATE,
      {
        RUNTIME_PROTOCOL_VERSION: enforceContract.identities.runtimeObserver,
        ERROR_CODES: errorCodes,
      }
    )],
    ["observer/protocol/schemas/heartbeat.schema.json", renderSchemaTemplate(
      HEARTBEAT_SCHEMA_TEMPLATE,
      {
        RUNTIME_PROTOCOL_PATTERN: runtimeProtocolPattern,
        RUNTIME_ERROR_CODES: runtimeErrorCodes,
      }
    )],
    ["observer/protocol/schemas/instance-registration.schema.json", renderSchemaTemplate(
      INSTANCE_REGISTRATION_SCHEMA_TEMPLATE,
      {
        RUNTIME_PROTOCOL_PATTERN: runtimeProtocolPattern,
        CAPABILITIES: capabilities,
      }
    )],
    ["observer/protocol/schemas/job-status.schema.json", renderSchemaTemplate(
      JOB_STATUS_SCHEMA_TEMPLATE,
      {
        RUNTIME_PROTOCOL_PATTERN: runtimeProtocolPattern,
        JOB_STATES: runtimeJobStates,
        RUNTIME_ERROR_CODES: runtimeErrorCodes,
      }
    )],
    ["observer/protocol/schemas/session-contract.schema.json", renderSchemaTemplate(
      SESSION_CONTRACT_SCHEMA_TEMPLATE,
      {
        RUNTIME_PROTOCOL_PATTERN: runtimeProtocolPattern,
        SESSION_DIRECTORY_NAME: sessionDirectoryName,
      }
    )],
    ["observer/protocol/schemas/vocabulary.schema.json", json(vocabularySchema)],
    ["observer/protocol/errors.md", renderErrorsMarkdown(errorEntries)],
    ["observer/protocol/capabilities.md", renderCapabilitiesMarkdown(capabilityEntries)],
  ]);
}

function artifactAbsolutePath(root: string, artifactPath: ProtocolArtifactPath): string {
  return join(root, ...artifactPath.split("/"));
}

export function writeProtocolArtifacts(
  root = repositoryRoot,
  source: ProtocolRegistrySource = CANONICAL_PROTOCOL_REGISTRIES
): void {
  for (const [artifactPath, contents] of renderProtocolArtifacts(source)) {
    const absolutePath = artifactAbsolutePath(root, artifactPath);
    mkdirSync(dirname(absolutePath), { recursive: true });
    writeFileSync(absolutePath, contents, "utf8");
  }
}

export function findProtocolArtifactDrift(
  root = repositoryRoot,
  source: ProtocolRegistrySource = CANONICAL_PROTOCOL_REGISTRIES
): ProtocolArtifactPath[] {
  const drifted: ProtocolArtifactPath[] = [];
  for (const [artifactPath, expected] of renderProtocolArtifacts(source)) {
    const absolutePath = artifactAbsolutePath(root, artifactPath);
    if (!existsSync(absolutePath) || readFileSync(absolutePath, "utf8") !== expected) {
      drifted.push(artifactPath);
    }
  }
  return drifted;
}

function main(): void {
  const arguments_ = process.argv.slice(2);
  const unknown = arguments_.filter((argument) => argument !== "--check");
  if (unknown.length > 0) {
    throw new Error(`Unknown argument(s): ${unknown.join(", ")}`);
  }

  if (arguments_.includes("--check")) {
    const drifted = findProtocolArtifactDrift();
    if (drifted.length > 0) {
      process.stderr.write([
        "Protocol artifacts are stale or missing:",
        ...drifted.map((path) => `  - ${path}`),
        "Run `npm run protocol:generate` and commit the resulting files.",
        "",
      ].join("\n"));
      process.exitCode = 1;
      return;
    }
    process.stdout.write(`Protocol artifacts are current (${PROTOCOL_ARTIFACT_PATHS.length} files).\n`);
    return;
  }

  writeProtocolArtifacts();
  process.stdout.write(
    `Generated ${PROTOCOL_ARTIFACT_PATHS.length} protocol artifacts under ${relative(repositoryRoot, join(repositoryRoot, "observer", "protocol"))}.\n`
  );
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    main();
  } catch (error) {
    process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
    process.exitCode = 1;
  }
}
